# Single character types
OPAREN		= "oparen"
CPAREN		= "cparen"
OBRACKET	= "obracket"
CBRACKET	= "cbracket"
COMMA		= "comma"
PLUS		= "plus"
MULTIPLY	= "multiply"
MINUS		= "minus"
DIVIDE		= "divide"
MODULUS		= "modulus"
EXPONENT	= "exponent"
LT			= "lt"
GT			= "gt"
ASSIGN		= "assign"
EQUALITY	= "equality"
COLON		= "colon"
SEMICOLON	= "semicolon"
VAR			= "var"

# Two character types
LTE			= "lte"
GTE			= "gte"
NOTEQUAL	= "notequal"

# Word types
IF			= "if"
FI			= "fi"
DO			= "do"
END			= "end"
ELIF		= "elif"
ELSE		= "else"
AND			= "and"
NOT			= "not"
OR			= "or"
NULL		= "null"
FOR			= "for"
WHILE		= "while"
CLASS		= "class"
BOOLTRUE	= "booltrue"
BOOLFALSE	= "boolfalse"
DEF			= "def"
THEN		= "then"
KEYWORD		= "keyword"
ARRAY		= "array"
PRINT		= "print"
RETURN		= "return"
EOF			= "EOF"
EPSILON		= "epsilon"

# Primaries
STRING      = "string"
INTEGER     = "integer"
REAL        = "real"
ID			= "id"

# The spooky *unknown*
UNKNOWN     = "unknown"